name = "zenemoo-pool-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "c3e84d8a84eaa06c632f189765eaa9c6"

[[d1_databases]]
binding = "DB"
database_name = "zenemoo-pools"
database_id = "4cd54d99-5404-4c3d-a722-ad6312645378"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "POOL_KV"
id = "ed397c25cba549b4b4b51d0992767c0e"

[vars]
CORS_ORIGIN = "https://zenemoo.in,https://www.zenemoo.in,https://web.zenemoo.in,https://app.zenemoo.in,http://localhost:5173,http://localhost:3000,http://localhost:5000"
JWT_SECRET = "zenemoo_super_secret_jwt_key_2026"
BREVO_API_KEY = "xkeysib-placeholder"
BREVO_SENDER_EMAIL = "noreply@zenemoo.in"
BREVO_SENDER_NAME = "Zenemoo Talent Network"

