name = "zenemoo-payment-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "c3e84d8a84eaa06c632f189765eaa9c6"

[[d1_databases]]
binding = "DB"
database_name = "zenemoo-payments"
database_id = "767e3dfb-3762-47e2-8a15-b7f786686fb5"

[vars]
CORS_ORIGIN = "https://zenemoo.in,https://www.zenemoo.in,https://web.zenemoo.in,http://localhost:5173,http://localhost:3000,http://localhost:5000"
SUPABASE_URL = "https://wkbkomwjuywdeaxgchxw.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrYmtvbXdqdXl3ZGVheGdjaHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxNjk2OTIsImV4cCI6MjEwMDc0NTY5Mn0.A9O0I0nzdWLrsULZEdL6GxUp4Ok3Y_QRbqCMJesXbM4"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrYmtvbXdqdXl3ZGVheGdjaHh3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTE2OTY5MiwiZXhwIjoyMTAwNzQ1NjkyfQ.rKHftyDY-Y65LIn-OvAZg3Gs4Xp0PTLwsmdDvUJbT9Q"

