name = "zenemoo-portfolio-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "c3e84d8a84eaa06c632f189765eaa9c6"

[[r2_buckets]]
binding = "PORTFOLIO_BUCKET"
bucket_name = "zenemoo-portfolio-storage"

[[d1_databases]]
binding = "DB"
database_name = "zenemoo-portfolio"

[vars]
CORS_ORIGIN = "https://zenemoo.in,https://www.zenemoo.in,https://web.zenemoo.in,https://app.zenemoo.in,http://localhost:5173,http://localhost:3000,http://localhost:5000"
JWT_SECRET = "zenemoo_super_secret_jwt_key_2026"
PUBLIC_CDN_BASE_URL = "https://cdn.zenemoo.in"
